import { signIn, signUp, signOut } from '../../store/auth/actions';
import { SIGN_IN, SIGN_UP, SIGN_OUT } from '../../store/auth/types';

describe('auth actions', () => {
    it('should sign in', () => {
        const token = 'autogeneratedtoken';
        const expectedAction = {
            type: SIGN_IN,
            payload: {
                token
            }
        }
        expect(signIn(token)).toEqual(expectedAction);
    });
    it('should sign up', () => {
        const token = 'autogeneratedtoken';
        const expectedAction = {
            type: SIGN_UP,
            payload: {
                token
            }
        }
        expect(signUp(token)).toEqual(expectedAction);
    });
    it('should sign out', () => {
        const expectedAction = {
            type: SIGN_OUT
        }
        expect(signOut()).toEqual(expectedAction);
    });
});